name: distress_signal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0                    # HTTP API calls to backend
  sensors_plus: ^4.0.2            # accelerometer for zero-touch
  geolocator: ^11.0.0             # GPS for lat/lng in SOS payload
  permission_handler: ^11.3.1     # runtime permission requests
  flutter_foreground_task: ^9.2.1 # Android foreground service + WAKE_LOCK
  shared_preferences: ^2.5.4      # persist settings across restarts
  flutter_blue_plus: ^2.2.1       # BLE advertising + scanning for Sonic Cascade
  
  # Firebase dependencies for Two-Way Push Notifications
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true